// Generated by converter/app/publish/generate-intellisense-helpers.mjs - do not edit manually

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type _attrIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js')._attr

/**
 * summary: Electrical Properties
 * description: Schema describing the electrical child-object of a Vessel.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 22
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9]+$)
 * provenance: source: src/lib/schemas/electrical/electrical.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AcQualitiesIntellisense = import('../../src/lib/schemas/electrical/electrical.js').AcQualities

/**
 * summary: Aircraft
 * description: metadata unavailable from specification export
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/non-vessel-variants/aircraft.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AircraftIntellisense = import('../../src/lib/schemas/non-vessel-variants/aircraft.js').Aircraft

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AircraftMmsiIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').AircraftMmsi

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AlarmMethodEnumIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').AlarmMethodEnum

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AlarmStateIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').AlarmState

/**
 * summary: Aton
 * description: metadata unavailable from specification export
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/non-vessel-variants/aton.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AtonIntellisense = import('../../src/lib/schemas/non-vessel-variants/aton.js').Aton

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type AtonMmsiIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').AtonMmsi

/**
 * summary: Electrical Properties
 * description: Schema describing the electrical child-object of a Vessel.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 22
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9]+$)
 * provenance: source: src/lib/schemas/electrical/electrical.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ChargerQualitiesIntellisense = import('../../src/lib/schemas/electrical/electrical.js').ChargerQualities

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type CommonValueFieldsIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').CommonValueFields

/**
 * summary: communication
 * description: Callsign for HF communication
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers detected: 8
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/communication-sensors-sources/communication.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type CommunicationIntellisense = import('../../src/lib/schemas/communication-sensors-sources/communication.js').Communication

/**
 * summary: anchor
 * description: The anchor data, for anchor watch etc
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 59
 * default: default markers not detected
 * examples: example markers detected: 4
 * format: formats: date-time
 * pattern: patterns: .*Z$
 * provenance: source: src/lib/schemas/navigation/navigation.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type CourseIntellisense = import('../../src/lib/schemas/navigation/navigation.js').Course

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type DatetimeValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').DatetimeValue

/**
 * summary: Electrical Properties
 * description: Schema describing the electrical child-object of a Vessel.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 22
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9]+$)
 * provenance: source: src/lib/schemas/electrical/electrical.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type DcQualitiesIntellisense = import('../../src/lib/schemas/electrical/electrical.js').DcQualities

/**
 * summary: SignalK Delta message schema
 * description: The context path of the updates, eg. the top level path plus object identifier.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers detected: 5
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/messaging/delta.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type DeltaIntellisense = import('../../src/lib/schemas/messaging/delta.js').Delta

/**
 * summary: design
 * description: The ship type number
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 78
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/tanks-design/design.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type DesignIntellisense = import('../../src/lib/schemas/tanks-design/design.js').Design

/**
 * summary: SignalK Discovery
 * description: The name of a group of endpoints at the same version level
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/messaging/discovery.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type DiscoveryIntellisense = import('../../src/lib/schemas/messaging/discovery.js').Discovery

/**
 * summary: Electrical Properties
 * description: Schema describing the electrical child-object of a Vessel.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 22
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9]+$)
 * provenance: source: src/lib/schemas/electrical/electrical.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ElectricalIntellisense = import('../../src/lib/schemas/electrical/electrical.js').Electrical

/**
 * summary: depth
 * description: The speed component of the water current vector
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 3
 * default: default markers detected: 1
 * examples: example markers detected: 9
 * format: formats not detected
 * pattern: patterns: [A-Za-z0-9]+, ^[a-zA-Z0-9/+-]+$
 * provenance: source: src/lib/schemas/environment/environment.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type EnvironmentIntellisense = import('../../src/lib/schemas/environment/environment.js').Environment

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type GeohashIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Geohash

/**
 * summary: SignalK Websockets Hello message schema
 * description: The name of the Signal K server software
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=2, maxItems=2; required markers=0
 * enum: literal options detected: 4
 * default: default markers not detected
 * examples: example markers detected: 1
 * format: formats: signalk-self-vessel-id, signalk-self-aircraft-id, signalk-self-aton-id, signalk-self-sar-id
 * pattern: patterns: ^vessels.(urn:mrn:(imo:mmsi:[2-7][0-9]{8}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$, ^aircraft.(urn:mrn:(imo:mmsi:1[0-9]{8}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$, ^aton.(urn:mrn:(imo:mmsi:99[0-9]{7}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$, ^sar.(urn:mrn:(imo:mmsi:97[0-9]{7}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$
 * provenance: source: src/lib/schemas/messaging/hello.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type HelloIntellisense = import('../../src/lib/schemas/messaging/hello.js').Hello

/**
 * summary: Electrical Properties
 * description: Schema describing the electrical child-object of a Vessel.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 22
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9]+$)
 * provenance: source: src/lib/schemas/electrical/electrical.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type IdentityIntellisense = import('../../src/lib/schemas/electrical/electrical.js').Identity

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type MetaIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Meta

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type MmsiIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Mmsi

/**
 * summary: anchor
 * description: The anchor data, for anchor watch etc
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 59
 * default: default markers not detected
 * examples: example markers detected: 4
 * format: formats: date-time
 * pattern: patterns: .*Z$
 * provenance: source: src/lib/schemas/navigation/navigation.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type NavigationIntellisense = import('../../src/lib/schemas/navigation/navigation.js').Navigation

/**
 * summary: notifications
 * description: Message to display or speak
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^((?!^mob$|^fire$|^sinking$|^flooding$|^collision$|^grounding$|^listing$|^adrift$|^piracy$|^abandon$)[A-Za-z0-9-])+$)
 * provenance: source: src/lib/schemas/notifications/notifications.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type NotificationIntellisense = import('../../src/lib/schemas/notifications/notifications.js').Notification

/**
 * summary: notifications
 * description: Message to display or speak
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^((?!^mob$|^fire$|^sinking$|^flooding$|^collision$|^grounding$|^listing$|^adrift$|^piracy$|^abandon$)[A-Za-z0-9-])+$)
 * provenance: source: src/lib/schemas/notifications/notifications.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type NotificationBranchIntellisense = import('../../src/lib/schemas/notifications/notifications.js').NotificationBranch

/**
 * summary: notifications
 * description: Message to display or speak
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^((?!^mob$|^fire$|^sinking$|^flooding$|^collision$|^grounding$|^listing$|^adrift$|^piracy$|^abandon$)[A-Za-z0-9-])+$)
 * provenance: source: src/lib/schemas/notifications/notifications.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type NotificationsIntellisense = import('../../src/lib/schemas/notifications/notifications.js').Notifications

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type NullValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').NullValue

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type NumberValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').NumberValue

/**
 * summary: performance
 * description: The UUID of the active polar table
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=3, maxItems=5; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$
 * provenance: source: src/lib/schemas/sails-performance/performance.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type PerformanceIntellisense = import('../../src/lib/schemas/sails-performance/performance.js').Performance

/**
 * summary: performance
 * description: The UUID of the active polar table
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=3, maxItems=5; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$
 * provenance: source: src/lib/schemas/sails-performance/performance.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type PolarIntellisense = import('../../src/lib/schemas/sails-performance/performance.js').Polar

/**
 * summary: performance
 * description: The UUID of the active polar table
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=3, maxItems=5; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$
 * provenance: source: src/lib/schemas/sails-performance/performance.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type PolarUuidIntellisense = import('../../src/lib/schemas/sails-performance/performance.js').PolarUuid

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type PositionIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Position

/**
 * summary: Propulsion
 * description: Data about the engine's drive.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 18
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9]+$)
 * provenance: source: src/lib/schemas/propulsion-steering/propulsion.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type PropulsionIntellisense = import('../../src/lib/schemas/propulsion-steering/propulsion.js').Propulsion

/**
 * summary: Polygon
 * description: Identifier for the layer.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=3, maxItems=0; required markers=0
 * enum: literal options detected: 21
 * default: default markers not detected
 * examples: example markers detected: 5
 * format: formats not detected
 * pattern: patterns: (^[A-Za-z0-9_-]{8,}$), ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$
 * provenance: source: src/lib/schemas/resources/resources.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ResourcesIntellisense = import('../../src/lib/schemas/resources/resources.js').Resources

/**
 * summary: sails
 * description: An object containing information about the vessels' sails.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers detected: 4
 * examples: example markers detected: 4
 * format: formats not detected
 * pattern: patterns: (^[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/sails-performance/sails.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SailsIntellisense = import('../../src/lib/schemas/sails-performance/sails.js').Sails

/**
 * summary: Sar
 * description: metadata unavailable from specification export
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/non-vessel-variants/sar.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SarIntellisense = import('../../src/lib/schemas/non-vessel-variants/sar.js').Sar

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SarMmsiIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').SarMmsi

/**
 * summary: sensor
 * description: The common name of the sensor
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/communication-sensors-sources/sensors.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SensorsIntellisense = import('../../src/lib/schemas/communication-sensors-sources/sensors.js').Sensors

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SourceIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Source

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SourceRefIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').SourceRef

/**
 * summary: Sources
 * description: Sources unique name e.g. [type-bus].[id], N2000-01.034
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers detected: 2
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/communication-sensors-sources/sources.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SourcesIntellisense = import('../../src/lib/schemas/communication-sensors-sources/sources.js').Sources

/**
 * summary: target
 * description: Autopilot target
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 11
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/propulsion-steering/steering.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type SteeringIntellisense = import('../../src/lib/schemas/propulsion-steering/steering.js').Steering

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type StringValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').StringValue

/**
 * summary: TankCollection
 * description: A tank, named by a unique identifier
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 11
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/tanks-design/tanks.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type TankCollectionIntellisense = import('../../src/lib/schemas/tanks-design/tanks.js').TankCollection

/**
 * summary: Tanks
 * description: A tank, named by a unique identifier
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 11
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/tanks-design/tanks.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type TanksIntellisense = import('../../src/lib/schemas/tanks-design/tanks.js').Tanks

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type TimestampIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Timestamp

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type UnitsIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Units

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type UrlIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Url

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type UuidIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Uuid

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ValuesDatetimeValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').ValuesDatetimeValue

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ValuesNumberValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').ValuesNumberValue

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ValuesStringValueIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').ValuesStringValue

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type VersionIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Version

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type WaypointIntellisense = import('../../src/lib/schemas/foundation/foundation-definitions.js').Waypoint

/**
 * summary: depth
 * description: The speed component of the water current vector
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options detected: 3
 * default: default markers detected: 1
 * examples: example markers detected: 9
 * format: formats not detected
 * pattern: patterns: [A-Za-z0-9]+, ^[a-zA-Z0-9/+-]+$
 * provenance: source: src/lib/schemas/environment/environment.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type ZoneObjectIntellisense = import('../../src/lib/schemas/environment/environment.js').ZoneObject
