// Generated by converter/app/publish/generate-intellisense-helpers.mjs - do not edit manually

/**
 * summary: SignalK Websockets Hello message schema
 * description: The name of the Signal K server software
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=2, maxItems=2; required markers=0
 * enum: literal options detected: 4
 * default: default markers not detected
 * examples: example markers detected: 1
 * format: formats: signalk-self-vessel-id, signalk-self-aircraft-id, signalk-self-aton-id, signalk-self-sar-id
 * pattern: patterns: ^vessels.(urn:mrn:(imo:mmsi:[2-7][0-9]{8}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$, ^aircraft.(urn:mrn:(imo:mmsi:1[0-9]{8}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$, ^aton.(urn:mrn:(imo:mmsi:99[0-9]{7}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$, ^sar.(urn:mrn:(imo:mmsi:97[0-9]{7}$|signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$))|(http(s?):.*|mailto:.*|tel:(\+?)[0-9]{4,})$
 * provenance: source: src/lib/schemas/messaging/hello.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type Hello = import('../schemas/messaging/hello.js').Hello

/**
 * summary: SignalK Discovery
 * description: The name of a group of endpoints at the same version level
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers not detected
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/messaging/discovery.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type Discovery = import('../schemas/messaging/discovery.js').Discovery

/**
 * summary: SignalK Delta message schema
 * description: The context path of the updates, eg. the top level path plus object identifier.
 * constraints: numeric bounds markers: min=0, max=0, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=0, maxItems=0; required markers=0
 * enum: literal options not detected
 * default: default markers not detected
 * examples: example markers detected: 5
 * format: formats not detected
 * pattern: patterns not detected
 * provenance: source: src/lib/schemas/messaging/delta.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type Delta = import('../schemas/messaging/delta.js').Delta
