// Generated by converter/app/publish/generate-intellisense-helpers.mjs - do not edit manually

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type Position = import('../schemas/foundation/foundation-definitions.js').Position

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type Waypoint = import('../schemas/foundation/foundation-definitions.js').Waypoint

/**
 * summary: _group schema.
 * description: The group owning this resource.
 * constraints: numeric bounds markers: min=1, max=1, exMin=0, exMax=0; size markers: minLength=0, maxLength=0, minItems=1, maxItems=0; required markers=0
 * enum: literal options detected: 14
 * default: default markers detected: 5
 * examples: example markers detected: 39
 * format: formats: signalk-aircraft-mmsi, signalk-aton-mmsi, signalk-source-ref, date-time, signalk-geohash, signalk-vessel-mmsi, signalk-sar-mmsi, signalk-uuid-urn, signalk-version
 * pattern: patterns: ^1[0-9]{8}$, ^99[0-9]{7}$, ^[A-Za-z0-9-_.]*$, .*Z$, ^[0-9A-Za-z:]{1,}$, ^[2-7][0-9]{8}$, ^97[0-9]{7}$, ^urn:mrn:signalk:uuid:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$, ^[0-9]{1,3}[.][0-9]{1,2}[.][0-9]{1,2}($|-[a-zA-Z0-9]+$)
 * provenance: source: src/lib/schemas/foundation/foundation-definitions.ts
 * lifecycle: deprecated markers=0, readOnly markers=0, writeOnly markers=0
 */
export type Geohash = import('../schemas/foundation/foundation-definitions.js').Geohash
