import { createHash } from 'node:crypto'
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { GROUPS } from '../config/groups.mjs'
import { repoRoot, runNodeScript, runtimeFormatsOutputFile, schemaArtifactsRoot, schemaDiagnosticsRoot } from '../core/runtime.mjs'

const LIB_ROOT = path.join(repoRoot, 'src/lib')
const LIB_SCHEMAS_ROOT = path.join(LIB_ROOT, 'schemas')
const LIB_INTELLISENSE_ROOT = path.join(LIB_ROOT, 'intellisense')
const LIB_INTELLISENSE_ROOT_REL = 'src/lib/intellisense'
const INTELLISENSE_OUTPUT_DIR = path.join(repoRoot, 'converter/intellisenseOutput')
const TYPEHELPERS_REPORT_FILE = path.join(repoRoot, 'converter/intellisenseDiagnostic/typehelpers-report.json')
const LIB_FORMATS_FILE = path.join(LIB_ROOT, 'formats.ts')
const PUBLISH_MANIFEST_FILE = path.join(schemaDiagnosticsRoot, 'schema-publish-manifest.json')

const FACADE_SPEC = {
  transport: ['Hello', 'Discovery', 'Delta', 'Source', 'SourceRef', 'Timestamp'],
  values: ['NumberValue', 'StringValue', 'DatetimeValue', 'NullValue', 'ValuesNumberValue', 'ValuesStringValue', 'ValuesDatetimeValue'],
  meta: ['Meta', 'AlarmState', 'AlarmMethodEnum', 'Units'],
  spatial: ['Position', 'Waypoint', 'Geohash'],
  identity: ['Mmsi', 'AircraftMmsi', 'AtonMmsi', 'SarMmsi', 'Uuid', 'Url', 'Version'],
  protocol: ['Hello', 'Discovery', 'Delta']
}

async function pathExists(filePath) {
  try {
    await stat(filePath)
    return true
  } catch {
    return false
  }
}

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, 'utf8'))
}

function sha256(input) {
  const hash = createHash('sha256')
  hash.update(input)
  return hash.digest('hex')
}

async function collectManifestDebt() {
  const debt = []
  const manifests = []

  for (const group of GROUPS) {
    const manifestPath = path.join(schemaArtifactsRoot, group.name, 'manifest.json')
    if (!(await pathExists(manifestPath))) {
      debt.push(`missing manifest for ${group.name}: ${path.relative(repoRoot, manifestPath)}`)
      continue
    }

    const manifest = await readJson(manifestPath)
    manifests.push({ group: group.name, manifestPath, manifest })

    const warnings = Array.isArray(manifest.warnings) ? manifest.warnings : []
    const exceptions = Array.isArray(manifest.exceptions) ? manifest.exceptions : []

    if (warnings.length > 0) {
      debt.push(`${group.name}: ${warnings.length} warning(s)`)
    }
    if (exceptions.length > 0) {
      debt.push(`${group.name}: ${exceptions.length} exception(s)`)
    }
  }

  return { debt, manifests }
}

async function copySchemasToLibrary() {
  await rm(LIB_SCHEMAS_ROOT, { recursive: true, force: true })
  await mkdir(LIB_SCHEMAS_ROOT, { recursive: true })

  const promoted = []
  for (const group of GROUPS) {
    const fromDir = path.join(schemaArtifactsRoot, group.name)
    const toDir = path.join(LIB_SCHEMAS_ROOT, group.name)
    await cp(fromDir, toDir, { recursive: true })
    promoted.push({ group: group.name, fromDir, toDir })
  }

  return promoted
}

async function indexPromotedSymbols() {
  const bySymbol = new Map()

  async function walk(dirPath) {
    const entries = await readdir(dirPath, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name)
      if (entry.isDirectory()) {
        await walk(fullPath)
        continue
      }
      if (!entry.name.endsWith('.ts')) continue
      if (entry.name === 'manifest.json') continue

      const relFromRepo = path.relative(repoRoot, fullPath)
      const source = await readFile(fullPath, 'utf8')
      const typeMatches = [...source.matchAll(/export\s+type\s+([A-Za-z0-9_]+)\s*=/g)]
      for (const match of typeMatches) {
        const symbol = match[1]
        bySymbol.set(symbol, relFromRepo)
      }
    }
  }

  await walk(LIB_SCHEMAS_ROOT)
  return bySymbol
}

function relImport(fromFile, targetRepoRelPath) {
  const fromDir = path.dirname(path.join(repoRoot, fromFile))
  const targetAbs = path.join(repoRoot, targetRepoRelPath)
  const rel = path.relative(fromDir, targetAbs).replace(/\\/g, '/')
  return rel.startsWith('.') ? rel : `./${rel}`
}

async function writeFacades(symbolIndex) {
  const missing = []
  const facadesRoot = path.join(LIB_ROOT, 'facades')
  await mkdir(facadesRoot, { recursive: true })

  for (const [facadeName, symbols] of Object.entries(FACADE_SPEC)) {
    const facadeRelPath = path.join('src/lib/facades', `${facadeName}.ts`)
    const lines = [
      '// Generated by converter/app/cli/publish.mjs - do not edit manually',
      ''
    ]

    for (const symbol of symbols) {
      const sourceRel = symbolIndex.get(symbol)
      if (!sourceRel) {
        missing.push(`${facadeName}: missing symbol ${symbol}`)
        continue
      }
      const importPath = relImport(facadeRelPath, sourceRel).replace(/\.ts$/, '.js')
      lines.push(`export { ${symbol}Schema } from '${importPath}'`)
      lines.push(`export type { ${symbol} } from '${importPath}'`)
      lines.push('')
    }

    await writeFile(path.join(repoRoot, facadeRelPath), `${lines.join('\n')}\n`, 'utf8')
  }

  if (missing.length > 0) {
    throw new Error(`Facade generation failed:\n- ${missing.join('\n- ')}`)
  }
}

async function promoteFormats() {
  if (!(await pathExists(runtimeFormatsOutputFile))) {
    throw new Error(`Missing runtime formats source: ${path.relative(repoRoot, runtimeFormatsOutputFile)}`)
  }
  await mkdir(path.dirname(LIB_FORMATS_FILE), { recursive: true })
  await cp(runtimeFormatsOutputFile, LIB_FORMATS_FILE)
}

async function promoteIntellisense() {
  if (!(await pathExists(INTELLISENSE_OUTPUT_DIR))) {
    throw new Error(`Missing intellisense output dir: ${path.relative(repoRoot, INTELLISENSE_OUTPUT_DIR)}`)
  }
  await rm(LIB_INTELLISENSE_ROOT, { recursive: true, force: true })
  await mkdir(LIB_INTELLISENSE_ROOT, { recursive: true })

  const entries = await readdir(INTELLISENSE_OUTPUT_DIR, { withFileTypes: true })
  for (const entry of entries) {
    if (!entry.isFile()) continue
    if (!entry.name.endsWith('.ts')) continue
    const fromFile = path.join(INTELLISENSE_OUTPUT_DIR, entry.name)
    const toFile = path.join(LIB_INTELLISENSE_ROOT, entry.name)
    await cp(fromFile, toFile)
  }
}

async function readTypehelpersReport() {
  if (!(await pathExists(TYPEHELPERS_REPORT_FILE))) {
    throw new Error(`Missing typehelpers report: ${path.relative(repoRoot, TYPEHELPERS_REPORT_FILE)}`)
  }
  return readJson(TYPEHELPERS_REPORT_FILE)
}

async function writePublishManifest({ promoted, intellisenseReport }) {
  const manifest = {
    version: 1,
    generatedAt: '1970-01-01T00:00:00.000Z',
    strictGate: 'fail-on-warnings-and-exceptions',
    sources: {
      schemaArtifactsRoot: path.relative(repoRoot, schemaArtifactsRoot),
      runtimeFormatsOutputFile: path.relative(repoRoot, runtimeFormatsOutputFile)
    },
    targets: {
      librarySchemasRoot: path.relative(repoRoot, LIB_SCHEMAS_ROOT),
      libraryFormatsFile: path.relative(repoRoot, LIB_FORMATS_FILE),
      intellisenseRoot: LIB_INTELLISENSE_ROOT_REL
    },
    promotedGroups: promoted.map((item) => item.group),
    facades: Object.keys(FACADE_SPEC),
    intellisense: {
      groups: Object.keys(FACADE_SPEC),
      manifestFile: path.relative(repoRoot, intellisenseReport.manifestFile),
      manifestHash: intellisenseReport.manifestHash,
      symbolCount: intellisenseReport.symbolCount,
      groupCount: intellisenseReport.groupCount,
      unresolvedMetadata: intellisenseReport.unresolvedMetadata
    }
  }

  await mkdir(path.dirname(PUBLISH_MANIFEST_FILE), { recursive: true })
  await writeFile(PUBLISH_MANIFEST_FILE, JSON.stringify(manifest, null, 2), 'utf8')

  const manifestSource = JSON.stringify(manifest)
  return {
    file: PUBLISH_MANIFEST_FILE,
    hash: sha256(manifestSource)
  }
}

async function main() {
  const args = process.argv.slice(2)
  const forceMode = args.includes('--force')
  
  if (forceMode) {
    console.warn('⚠️  WARNING: --force flag detected. Bypassing strict gate checks.')
  }

  console.log('Running preflight schema verification...')
  runNodeScript('converter/app/cli/verify.mjs')

  const { debt } = await collectManifestDebt()
  if (debt.length > 0) {
    if (forceMode) {
      console.warn('⚠️  Strict gate warnings/exceptions detected (ignored due to --force):')
      for (const line of debt) {
        console.warn(`  - ${line}`)
      }
    } else {
      console.error('schema:publish blocked by strict gate (warnings/exceptions not allowed):')
      for (const line of debt) {
        console.error(`- ${line}`)
      }
      console.error('\nTo skip this check during testing, use: npm run schema:publish -- --force')
      process.exit(1)
    }
  }

  console.log('Promoting schema outputs into src/lib...')
  const promoted = await copySchemasToLibrary()

  console.log('Promoting runtime formats...')
  await promoteFormats()

  console.log('Indexing promoted symbols...')
  const symbolIndex = await indexPromotedSymbols()

  console.log('Generating facade modules...')
  await writeFacades(symbolIndex)

  console.log('Generating sidecar JSDoc/IntelliSense helpers...')
  runNodeScript('converter/app/cli/typehelpers.mjs')
  const intellisenseReport = await readTypehelpersReport()

  console.log('Promoting IntelliSense helpers into src/lib/intellisense...')
  await promoteIntellisense()

  console.log('Writing publish manifest...')
  const publishManifest = await writePublishManifest({ promoted, intellisenseReport })

  console.log(`schema:publish complete.`)
  console.log(`Publish manifest: ${path.relative(repoRoot, publishManifest.file)}`)
  console.log(`Publish manifest hash: ${publishManifest.hash}`)
  console.log('Manual next step: run npm run build && npm run test')
}

await main()
